title: Raspberry Pi Foundation Scratch Style Guide
hero_image: images/banner.png
description: default-project-template description
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: Style Guide
